# Packs the trimmed frame images into assets\frames\frames-data.js as JPEG
# data URIs.
#
# Why: a page opened with file:// taints its canvas as soon as it draws an
# image loaded from a separate file, and a tainted canvas refuses toDataURL --
# so the finished photo can never be produced. A data: URI counts as
# same-origin, so the canvas stays clean and file:// works.
#
# A classic <script src> tag still loads fine from file://, which is why the
# payload ships as .js rather than being fetched.
#
# Usage: powershell -ExecutionPolicy Bypass -File tools\pack-frames.ps1
# Re-run after changing any frame PNG.
#
# ASCII only: PowerShell 5.1 reads this file as ANSI.

param([int]$Quality = 88)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$dir  = Join-Path $root "assets\frames"

$jpegCodec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() |
             Where-Object { $_.MimeType -eq "image/jpeg" }
$encParams = New-Object System.Drawing.Imaging.EncoderParameters 1
$encParams.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter (
    [System.Drawing.Imaging.Encoder]::Quality, [long]$Quality)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Generated by tools\pack-frames.ps1 - do not edit by hand.")
[void]$sb.AppendLine("// Frame artwork inlined so the app also works when opened as a plain file.")
[void]$sb.AppendLine("window.FRAME_DATA = {")

# 총학생회(기본) 프레임만 심는다. 단과대 프레임 32장까지 심으면 8MB 가 되어
# 페이지가 못 뜨므로, 나머지는 파일로 불러온다.
$names = @("chonghak-4cut", "chonghak-3cut")
$files = @{ "chonghak-4cut" = "chonghak-4cut.jpg"; "chonghak-3cut" = "chonghak-3cut.jpg" }

foreach ($key in $names) {
  $path = Join-Path $dir $files[$key]
  $bmp = New-Object System.Drawing.Bitmap $path

  # flatten onto black first: JPEG has no alpha channel
  $flat = New-Object System.Drawing.Bitmap $bmp.Width, $bmp.Height,
          ([System.Drawing.Imaging.PixelFormat]::Format24bppRgb)
  $g = [System.Drawing.Graphics]::FromImage($flat)
  $g.Clear([System.Drawing.Color]::Black)
  $g.DrawImage($bmp, 0, 0, $bmp.Width, $bmp.Height)
  $g.Dispose()

  $ms = New-Object System.IO.MemoryStream
  $flat.Save($ms, $jpegCodec, $encParams)
  $bytes = $ms.ToArray()
  $ms.Dispose(); $flat.Dispose(); $bmp.Dispose()

  $b64 = [Convert]::ToBase64String($bytes)
  [void]$sb.AppendLine('  ' + $key + ': "data:image/jpeg;base64,' + $b64 + '",')

  Write-Output ("{0,-6} {1,7:N0} KB -> {2,7:N0} KB base64" -f `
    $key, ((Get-Item $path).Length / 1KB), ($b64.Length / 1KB))
}

[void]$sb.AppendLine("};")

$out = Join-Path $dir "frames-data.js"
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Output ("wrote " + $out + "  (" + [math]::Round((Get-Item $out).Length / 1KB) + " KB)")
